version: "3.8"

networks:
  nginx:
    name: net_nginx
    external: true

services:
  neko_bin_api:
    image: ghcr.io/atakku/neko_bin_api:latest
    container_name: neko_bin_api
    restart: unless-stopped
    networks:
      - nginx
  neko_bin_web:
    image: ghcr.io/atakku/neko_bin_web:latest
    container_name: neko_bin_web
    restart: unless-stopped
    networks:
      - nginx
