[package]
name = "neko_runtime"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
# local dependencies
neko_core.workspace = true
neko_db.workspace = true
neko_mods.workspace = true
# external dependencies
pretty_env_logger.workspace = true
tokio.workspace = true
